// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2wQ5Bof2CebGj_2RWQ-NXO_0rSgj35No',
    appId: '1:287632544949:web:0026329c962164734e5afc',
    messagingSenderId: '287632544949',
    projectId: 'doanflutter-bec18',
    authDomain: 'doanflutter-bec18.firebaseapp.com',
    storageBucket: 'doanflutter-bec18.firebasestorage.app',
    measurementId: 'G-QCDN0F3GM8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdRH0cGOKvBFqeUebtK6X5cGm5Ei575Ss',
    appId: '1:287632544949:ios:5e81e0ed9c30d31d4e5afc',
    messagingSenderId: '287632544949',
    projectId: 'doanflutter-bec18',
    storageBucket: 'doanflutter-bec18.firebasestorage.app',
    iosBundleId: 'com.example.doanflutter',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdRH0cGOKvBFqeUebtK6X5cGm5Ei575Ss',
    appId: '1:287632544949:ios:5e81e0ed9c30d31d4e5afc',
    messagingSenderId: '287632544949',
    projectId: 'doanflutter-bec18',
    storageBucket: 'doanflutter-bec18.firebasestorage.app',
    iosBundleId: 'com.example.doanflutter',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0CbapqnHlj_XUPLZjHsNCtt2VKJ5itxg',
    appId: '1:287632544949:android:7b41f1743062910e4e5afc',
    messagingSenderId: '287632544949',
    projectId: 'doanflutter-bec18',
    storageBucket: 'doanflutter-bec18.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2wQ5Bof2CebGj_2RWQ-NXO_0rSgj35No',
    appId: '1:287632544949:web:584fd3ddf9bb99bb4e5afc',
    messagingSenderId: '287632544949',
    projectId: 'doanflutter-bec18',
    authDomain: 'doanflutter-bec18.firebaseapp.com',
    storageBucket: 'doanflutter-bec18.firebasestorage.app',
    measurementId: 'G-V3VQTP7EP6',
  );

}